export const BASE_URL = ''
export const USERS_URL = '/api/users'
export const MOVIES_URL = '/api/movies'
export const UPLOAD_URL = '/api/upload' 
export const ORDERS_URL = '/api/orders'
export const PAYPAL_URL = '/api/config/paypal'